name:                Hangman
version:             0.1.0.0
github:              "CarstenKoenig/Hangman"
license:             BSD3
author:              "Carsten Koenig"
maintainer:          "Carsten.Koenig@hotmail.de"
copyright:           "2018 Carsten Koenig"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CarstenKoenig/Hangman#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  Hangman-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hangman
    - ansi-terminal
    - hidden-char

tests:
  Hangman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hangman
    - hspec
    - QuickCheck
